# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ayman Bagabas
author:
  name: Ayman Bagabas
  url: "https://aymanbagabas.com"
url: "https://aymanbagabas.com"
email: email@aymanbagabas.com
description: >
  Playground where I express ideas, share knowledge, and experiences.
baseurl: "" # the subpath of your site, e.g. /blog
repository: aymanbagabas/aymanbagabas.github.io

remote_theme: fongandrew/hydeout

disqus:
  shortname: "blog-aymanbagabas-com"
google_analytics: "UA-119528295-1"

twitter:
  username: aymanbagabas
  card: summary

github:
  username: aymanbagabas

linkedin:
  username: aymanbagabas

social:
  name: Ayman Bagabas
  username: aymanbagabas
  links:
    - https://twitter.com/aymanbagabas
    - https://github.com/aymanbagabas
    - https://linkedin.com/in/aymanbagabas
    - https://aymanbagabas.tumblr.com/

# Dirs
layout_dir: _layouts
posts_dir: _posts

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  parse_block_html: true
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - jekyll-github-metadata
  - jekyll-redirect-from
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - scripts
  - tumblr-import.rb
paginate: 5
paginate_path: "/page:num"
permalink: /:categories/:year/:month/:day/:title:output_ext

feed:
  path: /feed.xml

# Sidebar link settings
sidebar_home_link: true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
# page. If you change your paginate_path,
# set this to the root of the paginate_path
# to enable a separate blog link.
