# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ayman Bagabas
author: Ayman Bagabas
email: email@aymanbagabas.com
description: >
  ~
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://aymanbagabas.com" # the base hostname & protocol for your site, e.g. http://example.com
repository: aymanbagabas/aymanbagabas.github.io
sidenav:
  about: 
     title: "Contact me"
     path: "/contact/"
  blog:
    title: "Blog"
    path: "/blog/"
  blog_index:
    title: "Index"
    path: "/blog/posts.html"
  projects:
     title: "Projects"
     path: "/projects/"
twitter:
  username: aymanbagabas
social:
  name: Ayman Bagabas
  links:
    - https://twitter.com/aymanbagabas
    - https://github.com/aymanbagabas
disqus_shortname: "blog-aymanbagabas-com"
google_analytics: "UA-119528295-1"

# Dirs
layout_dir: _layouts
posts_dir: _posts

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  parse_block_html: true
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - jekyll-github-metadata
  - jekyll-redirect-from
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - scripts
excerpt_separator: "\n"
paginate: 5
paginate_path: "/blog/page:num"
permalink: /blog/:categories/:year/:month/:day/:title:output_ext

feed:
  path: /blog/feed.xml

theme: null