# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ayman Bagabas
author: Ayman Bagabas
email: email@aymanbagabas.com
description: > # this means to ignore newlines until "baseurl:"
  tech, code, misc.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://aymanbagabas.com" # the base hostname & protocol for your site, e.g. http://example.com
sidenav:
  about: 
     title: "About me"
     path: "/about/"
  blog:
    title: "Blog"
    path: "/"
  blog_index:
    title: "Blog index"
    path: "/posts.html"
  projects:
     title: "Projects"
     path: "/projects/"
twitter:
  username: aymanbagabas
github:
  username: aymanbagabas
social:
  name: Ayman Bagabas
  links:
    - https://twitter.com/aymanbagabas
    - https://github.com/aymanbagabas
disqus_shortname: "blog-aymanbagabas-com"
google_analytics: "UA-119528295-1"

# Dirs
layout_dir: _layouts
posts_dir: _posts

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
excerpt_separator: "\n"
