baseURL = "https://aymanbagabas.com/"
defaultContentLanguage = "en"
title = "Ayman Bagabas"
theme = "hyde"
enableEmoji = true
enableRobotsTXT = true
pluralizeListTitles = false

[pagination]
  pagerSize = 5
  path = "page"

[permalinks]
  blog = "/blog/:year/:month/:day/:slug/"

[taxonomies]
  tag = "tags"

[languages.en]
  locale = "en-us"
  weight = 1

[languages.en.params]
  description = "Playground where I express ideas, share knowledge, and experiences."

[services.disqus]
  shortname = "blog-aymanbagabas-com"

[services.googleAnalytics]
  ID = "UA-119528295-1"

[security]
  allowContent = ['text/markdown', 'text/html']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false
  [markup.highlight]
    style = "github"
    lineNos = false
    codeFences = true
    guessSyntax = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]

[author]
  name = "Ayman Bagabas"
  email = "email@aymanbagabas.com"

[params]
  description = "Playground where I express ideas, share knowledge, and experiences."
  themeColor = "theme-base-08"
  author = "Ayman Bagabas"
  authorURL = "https://aymanbagabas.com"
  github = "aymanbagabas"
  twitter = "aymanbagabas"
  linkedin = "aymanbagabas"
  copyright = "© 2017–2026 Ayman Bagabas"
  dateFormat = "January 2, 2006"

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 2

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 3

[[menu.main]]
  name = "Search"
  url = "/search/"
  weight = 4

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 5
