baseURL = "https://aymanbagabas.com/"
defaultContentLanguage = "en"
title = "Ayman Bagabas"
enableEmoji = true
enableRobotsTXT = true
pluralizeListTitles = false

[taxonomies]
  tag = "tags"

[permalinks]
  posts = "/posts/:year/:month/:day/:slug/"

[languages.en]
  locale = "en-us"
  weight = 1

[languages.en.params]
  description = "Personal site of Ayman Bagabas."

[services.googleAnalytics]
  ID = "G-5ZQY2F0YLT"

[services.disqus]
  shortname = "blog-aymanbagabas-com"

[security]
  allowContent = ['text/markdown', 'text/html']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false
  [markup.highlight]
    style = "bw"
    lineNos = false
    codeFences = true
    guessSyntax = true
    noClasses = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]

[author]
  name = "Ayman Bagabas"
  email = "email@aymanbagabas.com"

[params]
  description = "Personal site of Ayman Bagabas."
  author = "Ayman Bagabas"
  authorURL = "https://aymanbagabas.com"
  copyright = "© 2017–2026 Ayman Bagabas"
  dateFormat = "January 2, 2006"
